version: "3.5"

services:
  backend:
    build:
      context: .
      dockerfile: back-end.Dockerfile
    # restart: always
    ports:
      - "81:80"
    networks:
      - backend
  frontend:
    build:
      context: .
      dockerfile: front-end.Dockerfile
    ports:
      - "80:80"
  db:
    image: postgres:10.5-alpine
    restart: always
    environment:
      POSTGRES_USER: reddit-clone
      POSTGRES_PASSWORD: super-duper-secret
      POSTGRES_DB: reddit-clone
    networks:
      - backend
    volumes:
      - database_data:/var/lib/postgresql/data
  redis:
    image: redis:4.0.11-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - backend
    volumes:
      - redis_data:/data
  adminer:
    image: adminer:4.6.3-standalone
    restart: always
    networks:
      - backend
    ports:
      - "8080:8080"
  rediscommandor:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=backend:redis
    networks:
      - backend
    ports:
      - "8081:8081"

volumes:
  ? database_data
  ? redis_data

networks:
  ? backend
